### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by epicslapper** [so-much-meta/lczero_tools#5] opened 2018-05-18 08:37 UTC
HI ,

wanted to test some chess positions ran into some problems : 

test.py : could not find lztools directory so moved it up

weights file: get error message : FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Peter/git/leela-chess/release/weights.txt.gz'

so i created this directory , ( by the way in the repo :https://github.com/glinscott/leela-chess/

there is no such directory : release ) 

so i created this directory on my (windows ) machine : and added a weight file .

still this same message .

how can i change the code so the file can be found in the lczero tools directory ?

thanks, Peter

**Comment by trevor-graffa** [comment] 2018-05-18 23:24
I'm working on creating config, easier usage, doc, etc... Regardless, just change the weights file name in test.py to the full path and name of an actual weights file, and it should work (did you rename your weights file to "weights.txt.gz"?). Also, you can bypass the no lztools directory problem by either setting PYTHONPATH variable to the src directory, or running "pip install -e ." (which will do a "developer" install and link the directory to your python packages)

**Comment by epicslapper** [comment] 2018-05-20 13:07
That would be great , for now i changed the dir, and got past the white first move , then errors again. 
For now i give up...  ;-)
- another question : why is the mcts algoritm/file missing ?

**Comment by trevor-graffa** [comment] 2018-05-20 17:41
The point of this project is mostly as a means of experimenting with Leela's network (and eventually training data). That is, to be able to do analysis on the way its value and policy outputs are evolving, to investigate the way hidden layers work, etc. Perhaps add code to help the primary Leela-Chess devs with validation and regression testing. I'd like to add some sort of engine/MCTS, but that's not an immediate goal - other things to do first... Recently, I've been sidetracked from doing any other code-changes like I mentioned above because I'm investigating things like the impact on feeding Leela's network history vs no history (as the engine would see if FEN positions were provided).

If you're primarily interested in using Leela's MCTS engine, then I think http://lczero.org/ is really the place to go... That being said, I did add code to hook up to that engine via UCI (using python-chess) in the lczero/testing directory, and it also enables looking at policy/value outputs.

**Comment by trevor-graffa** [comment] 2018-05-21 05:19
I've added a config implementation, and more example usage here: https://github.com/so-much-meta/lczero_tools/blob/master/notebooks/Examples.ipynb

Closing this issue.

**Closed as completed by trevor-graffa** 2018-05-21 05:19 UTC
